add_watering:
  name: Add watering entry
  description: F체gt einen manuellen Bew채sserungseintrag hinzu und addiert ihn zur Gesamt-Wasserverbrauchsanzeige.
  fields:
    entity_id:
      name: Plant entity
      description: Die Pflanze oder der Cycle, f체r den der Eintrag hinzugef체gt wird
      required: true
      selector:
        entity:
          domain:
            - plant
            - cycle
          integration: plant
    amount_liters:
      name: Menge (L)
      description: Zu addierende Wassermenge in Litern
      example: 2
      required: true
      selector:
        number:
          min: 0
          max: 1000
          step: 0.1
          unit_of_measurement: L
          mode: box
    note:
      name: Notiz
      description: Optionaler Kommentar, der im Journal vermerkt wird
      required: false
      selector:
        text: