replace_sensor:
  description: Replaces an external sensor
  fields:
    meter_entity:
      description: The meter entity to replace the sensor for
      example: plant.my_plant_current_temperature
    new_sensor:
      description: Entity id of the new sensor
      example: sensor.new_temperature_outdoor
